#!/usr/bin/python

APP_BAR = "#212121"
APP_BG = "#303030"
APP_DIALOG = "#424242"
APP_FONT_COLOR = "#ffffff"

BUTTON_BG_COLOR_ACTIVE = "#3f51b5"
BUTTON_BG_COLOR_INACTIVE = APP_BG
#BUTTON_BG_COLOR_DISABLED = 

BUTTON_BG_COLOR_HOVER = APP_BG
BUTTON_BG_COLOR_NORMAL = APP_BG
BUTTON_FONT_COLOR = "#FFFFFF"
BUTTON_FONT_COLOR_HOVER_ACTIVE = APP_BG
BUTTON_FONT_COLOR_HOVER_INACTIVE = "#3f51b5"

BUTTON_BG_COLOR_LIGHTS = "#3F51B5"
BUTTON_BG_COLOR_LIGHTS_HOVER = "#1A237E"

BUTTON_FONT_COLOR_LIGHTS = "#FFFFFF"
BUTTON_FONT_COLOR_LIGHTS_HOVER = "#FFFFFF"

BUTTON_BG_COLOR_SENSORS = "#3F51B5"
BUTTON_FONT_COLOR_SENSORS = "#FFFFFF"

BUTTON_BG_COLOR_SENSORS_HOVER = "#1A237E"
BUTTON_FONT_COLOR_SENSORS_HOVER = "#FFFFFF"