.TH "Python Directory Reference" 3 "Thu May 25 2017" "Version 0.2" "SensorNode" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Python Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBopenhab\&.py\fP"
.br
.ti -1c
.RI "file \fBreadsensor\&.py\fP"
.br
.ti -1c
.RI "file \fBSensorNode\&.py\fP"
.br
.ti -1c
.RI "file \fBsensors\&.py\fP"
.br
.ti -1c
.RI "file \fBserialconnection\&.py\fP"
.br
.in -1c
