.TH "Python/ReadSensor Directory Reference" 3 "Mon Apr 3 2017" "Version 0.2" "SensorNode" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Python/ReadSensor Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBSensors\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fB__init__\&.py\fP"
.br
.ti -1c
.RI "file \fBReadSensor\&.py\fP"
.br
.ti -1c
.RI "file \fBSensorNode\&.py\fP"
.br
.ti -1c
.RI "file \fBSerialConnection\&.py\fP"
.br
.in -1c
