.TH "Python/old Directory Reference" 3 "Mon Apr 3 2017" "Version 0.2" "SensorNode" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Python/old Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBProtocol\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBBluetoothConn\&.py\fP"
.br
.ti -1c
.RI "file \fBConfigSensorNode\&.py\fP"
.br
.ti -1c
.RI "file \fBDesignColors\&.py\fP"
.br
.ti -1c
.RI "file \fBfindmyphone\&.py\fP"
.br
.ti -1c
.RI "file \fBNodeProtocol\&.py\fP"
.br
.ti -1c
.RI "file \fBReadSensor\&.py\fP"
.br
.ti -1c
.RI "file \fBreadSensorNode\&.py\fP"
.br
.ti -1c
.RI "file \fBsensLights\&.py\fP"
.br
.ti -1c
.RI "file \fBSensorNode\&.py\fP"
.br
.ti -1c
.RI "file \fBSensorNode0\&.py\fP"
.br
.ti -1c
.RI "file \fBSerialConn\&.py\fP"
.br
.in -1c
