.TH "BluetoothConn" 3 "Mon Apr 3 2017" "Version 0.2" "SensorNode" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BluetoothConn \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBBlueConnect\fP (MAC, port, timeOut)"
.br
.ti -1c
.RI "def \fBCloseConn\fP (s)"
.br
.ti -1c
.RI "def \fBReceiveData\fP (s, endStr)"
.br
.ti -1c
.RI "def \fBSendData\fP (s, string)"
.br
.ti -1c
.RI "def \fBReadSensorData\fP (bd_addr, send_str)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def BluetoothConn\&.BlueConnect ( MAC,  port,  timeOut)"

.SS "def BluetoothConn\&.CloseConn ( s)"

.SS "def BluetoothConn\&.ReadSensorData ( bd_addr,  send_str)"

.SS "def BluetoothConn\&.ReceiveData ( s,  endStr)"

.SS "def BluetoothConn\&.SendData ( s,  string)"

.SH "Author"
.PP 
Generated automatically by Doxygen for SensorNode from the source code\&.
