.TH "Python/old/BluetoothConn.py" 3 "Mon Apr 3 2017" "Version 0.2" "SensorNode" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Python/old/BluetoothConn.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBBluetoothConn\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBBluetoothConn\&.BlueConnect\fP (MAC, port, timeOut)"
.br
.ti -1c
.RI "def \fBBluetoothConn\&.CloseConn\fP (s)"
.br
.ti -1c
.RI "def \fBBluetoothConn\&.ReceiveData\fP (s, endStr)"
.br
.ti -1c
.RI "def \fBBluetoothConn\&.SendData\fP (s, string)"
.br
.ti -1c
.RI "def \fBBluetoothConn\&.ReadSensorData\fP (bd_addr, send_str)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SensorNode from the source code\&.
