.TH "bmp180_t" 3 "Thu May 25 2017" "Version 0.2" "SensorNode" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bmp180_t \- This structure holds \fBBMP180\fP initialization parameters\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <BMP180\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBbmp180_calib_param_t\fP \fBcalib_param\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBmode\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBchip_id\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBml_version\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBal_version\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBdev_addr\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBsensortype\fP"
.br
.ti -1c
.RI "\fBs32\fP \fBparam_b5\fP"
.br
.ti -1c
.RI "\fBs32\fP \fBnumber_of_samples\fP"
.br
.ti -1c
.RI "\fBs16\fP \fBoversamp_setting\fP"
.br
.ti -1c
.RI "\fBs16\fP \fBsw_oversamp\fP"
.br
.ti -1c
.RI "void(* \fBdelay_msec\fP )(\fBBMP180_MDELAY_DATA_TYPE\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This structure holds \fBBMP180\fP initialization parameters\&. 
.SH "Member Data Documentation"
.PP 
.SS "\fBu8\fP bmp180_t::al_version"
al version 
.SS "struct \fBbmp180_calib_param_t\fP bmp180_t::calib_param"
calibration data 
.SS "\fBu8\fP bmp180_t::chip_id"
chip id 
.SS "void(* bmp180_t::delay_msec) (\fBBMP180_MDELAY_DATA_TYPE\fP)"
delay function pointer 
.SS "\fBu8\fP bmp180_t::dev_addr"
device address 
.SS "\fBu8\fP bmp180_t::ml_version"
ml version 
.SS "\fBu8\fP bmp180_t::mode"
power mode 
.SS "\fBs32\fP bmp180_t::number_of_samples"
sample calculation 
.SS "\fBs16\fP bmp180_t::oversamp_setting"
oversampling setting 
.SS "\fBs32\fP bmp180_t::param_b5"
pram 
.SS "\fBu8\fP bmp180_t::sensortype"
sensor type 
.SS "\fBs16\fP bmp180_t::sw_oversamp"
software oversampling 

.SH "Author"
.PP 
Generated automatically by Doxygen for SensorNode from the source code\&.
