.TH "BMP180" 3 "Tue Mar 28 2017" "Version 0.2" "SensorNode" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BMP180 \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <BMP180\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBMP180\fP ()"
.br
.ti -1c
.RI "virtual \fB~BMP180\fP ()"
.br
.ti -1c
.RI "void \fBInit\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBBMP180\&.hpp\fP
.PP
Created on: 27 Mar 2017 Author: Matthias Minx 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "BMP180::BMP180 ()"

.SS "BMP180::~BMP180 ()\fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void BMP180::Init ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for SensorNode from the source code\&.
