.TH "bmp180_calib_param_t" 3 "Mon Mar 27 2017" "Version 0.1" "SensorNode" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bmp180_calib_param_t \- This structure holds all device specific calibration parameters\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <bmp180\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBs16\fP \fBac1\fP"
.br
.ti -1c
.RI "\fBs16\fP \fBac2\fP"
.br
.ti -1c
.RI "\fBs16\fP \fBac3\fP"
.br
.ti -1c
.RI "\fBu16\fP \fBac4\fP"
.br
.ti -1c
.RI "\fBu16\fP \fBac5\fP"
.br
.ti -1c
.RI "\fBu16\fP \fBac6\fP"
.br
.ti -1c
.RI "\fBs16\fP \fBb1\fP"
.br
.ti -1c
.RI "\fBs16\fP \fBb2\fP"
.br
.ti -1c
.RI "\fBs16\fP \fBmb\fP"
.br
.ti -1c
.RI "\fBs16\fP \fBmc\fP"
.br
.ti -1c
.RI "\fBs16\fP \fBmd\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This structure holds all device specific calibration parameters\&. 
.SH "Member Data Documentation"
.PP 
.SS "\fBs16\fP bmp180_calib_param_t::ac1"
calibration ac1 data 
.SS "\fBs16\fP bmp180_calib_param_t::ac2"
calibration ac2 data 
.SS "\fBs16\fP bmp180_calib_param_t::ac3"
calibration ac3 data 
.SS "\fBu16\fP bmp180_calib_param_t::ac4"
calibration ac4 data 
.SS "\fBu16\fP bmp180_calib_param_t::ac5"
calibration ac5 data 
.SS "\fBu16\fP bmp180_calib_param_t::ac6"
calibration ac6 data 
.SS "\fBs16\fP bmp180_calib_param_t::b1"
calibration b1 data 
.SS "\fBs16\fP bmp180_calib_param_t::b2"
calibration b2 data 
.SS "\fBs16\fP bmp180_calib_param_t::mb"
calibration mb data 
.SS "\fBs16\fP bmp180_calib_param_t::mc"
calibration mc data 
.SS "\fBs16\fP bmp180_calib_param_t::md"
calibration md data 

.SH "Author"
.PP 
Generated automatically by Doxygen for SensorNode from the source code\&.
