.TH "Python/old/ConfigSensorNode.py" 3 "Mon Apr 3 2017" "Version 0.2" "SensorNode" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Python/old/ConfigSensorNode.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBConfigSensorNode\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBConfigSensorNode\&.ConfigMACnRF\fP (sock, pipeNum, MAC)"
.br
.ti -1c
.RI "def \fBConfigSensorNode\&.ConfigBluetoothName\fP (sock, bt_name)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBConfigSensorNode\&.bt_addr\fP = '98:D3:31:FB:31:A6'"
.br
.ti -1c
.RI "int \fBConfigSensorNode\&.port\fP = 1"
.br
.ti -1c
.RI "int \fBConfigSensorNode\&.conn\fP = 0"
.br
.ti -1c
.RI "string \fBConfigSensorNode\&.out_str\fP = ''"
.br
.ti -1c
.RI "\fBConfigSensorNode\&.sock\fP = BlueConnect(bt_addr,port,5\&.0)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SensorNode from the source code\&.
