.TH "Python/old/DesignColors.py" 3 "Mon Apr 3 2017" "Version 0.2" "SensorNode" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Python/old/DesignColors.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBDesignColors\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBDesignColors\&.APP_BAR\fP = '#212121'"
.br
.ti -1c
.RI "string \fBDesignColors\&.APP_BG\fP = '#303030'"
.br
.ti -1c
.RI "string \fBDesignColors\&.APP_DIALOG\fP = '#424242'"
.br
.ti -1c
.RI "string \fBDesignColors\&.APP_FONT_COLOR\fP = '#ffffff'"
.br
.ti -1c
.RI "string \fBDesignColors\&.BUTTON_BG_COLOR_ACTIVE\fP = '#3f51b5'"
.br
.ti -1c
.RI "\fBDesignColors\&.BUTTON_BG_COLOR_INACTIVE\fP = APP_BG"
.br
.ti -1c
.RI "\fBDesignColors\&.BUTTON_BG_COLOR_HOVER\fP = APP_BG"
.br
.ti -1c
.RI "\fBDesignColors\&.BUTTON_BG_COLOR_NORMAL\fP = APP_BG"
.br
.ti -1c
.RI "string \fBDesignColors\&.BUTTON_FONT_COLOR\fP = '#FFFFFF'"
.br
.ti -1c
.RI "\fBDesignColors\&.BUTTON_FONT_COLOR_HOVER_ACTIVE\fP = APP_BG"
.br
.ti -1c
.RI "string \fBDesignColors\&.BUTTON_FONT_COLOR_HOVER_INACTIVE\fP = '#3f51b5'"
.br
.ti -1c
.RI "string \fBDesignColors\&.BUTTON_BG_COLOR_LIGHTS\fP = '#3F51B5'"
.br
.ti -1c
.RI "string \fBDesignColors\&.BUTTON_BG_COLOR_LIGHTS_HOVER\fP = '#1A237E'"
.br
.ti -1c
.RI "string \fBDesignColors\&.BUTTON_FONT_COLOR_LIGHTS\fP = '#FFFFFF'"
.br
.ti -1c
.RI "string \fBDesignColors\&.BUTTON_FONT_COLOR_LIGHTS_HOVER\fP = '#FFFFFF'"
.br
.ti -1c
.RI "string \fBDesignColors\&.BUTTON_BG_COLOR_SENSORS\fP = '#3F51B5'"
.br
.ti -1c
.RI "string \fBDesignColors\&.BUTTON_FONT_COLOR_SENSORS\fP = '#FFFFFF'"
.br
.ti -1c
.RI "string \fBDesignColors\&.BUTTON_BG_COLOR_SENSORS_HOVER\fP = '#1A237E'"
.br
.ti -1c
.RI "string \fBDesignColors\&.BUTTON_FONT_COLOR_SENSORS_HOVER\fP = '#FFFFFF'"
.br
.ti -1c
.RI "string \fBDesignColors\&.BUTTON_BG_COLOR_CONFIGURE\fP = '#2196f3'"
.br
.ti -1c
.RI "string \fBDesignColors\&.BUTTON_FONT_COLOR_CONFIGURE\fP = '#FFFFFF'"
.br
.ti -1c
.RI "string \fBDesignColors\&.BUTTON_BG_COLOR_CONFIGURE_HOVER\fP = '#0d47a1'"
.br
.ti -1c
.RI "string \fBDesignColors\&.BUTTON_FONT_COLOR_CONFIGURE_HOVER\fP = '#FFFFFF'"
.br
.ti -1c
.RI "string \fBDesignColors\&.BUTTON_BG_COLOR_SYSTEM\fP = '#2196f3'"
.br
.ti -1c
.RI "string \fBDesignColors\&.BUTTON_FONT_COLOR_SYSTEM\fP = '#FFFFFF'"
.br
.ti -1c
.RI "string \fBDesignColors\&.BUTTON_BG_COLOR_SYSTEM_HOVER\fP = '#0d47a1'"
.br
.ti -1c
.RI "string \fBDesignColors\&.BUTTON_FONT_COLOR_SYSTEM_HOVER\fP = '#FFFFFF'"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SensorNode from the source code\&.
