.TH "DesignColors" 3 "Mon Apr 3 2017" "Version 0.2" "SensorNode" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DesignColors \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBAPP_BAR\fP = '#212121'"
.br
.ti -1c
.RI "string \fBAPP_BG\fP = '#303030'"
.br
.ti -1c
.RI "string \fBAPP_DIALOG\fP = '#424242'"
.br
.ti -1c
.RI "string \fBAPP_FONT_COLOR\fP = '#ffffff'"
.br
.ti -1c
.RI "string \fBBUTTON_BG_COLOR_ACTIVE\fP = '#3f51b5'"
.br
.ti -1c
.RI "\fBBUTTON_BG_COLOR_INACTIVE\fP = \fBAPP_BG\fP"
.br
.ti -1c
.RI "\fBBUTTON_BG_COLOR_HOVER\fP = \fBAPP_BG\fP"
.br
.ti -1c
.RI "\fBBUTTON_BG_COLOR_NORMAL\fP = \fBAPP_BG\fP"
.br
.ti -1c
.RI "string \fBBUTTON_FONT_COLOR\fP = '#FFFFFF'"
.br
.ti -1c
.RI "\fBBUTTON_FONT_COLOR_HOVER_ACTIVE\fP = \fBAPP_BG\fP"
.br
.ti -1c
.RI "string \fBBUTTON_FONT_COLOR_HOVER_INACTIVE\fP = '#3f51b5'"
.br
.ti -1c
.RI "string \fBBUTTON_BG_COLOR_LIGHTS\fP = '#3F51B5'"
.br
.ti -1c
.RI "string \fBBUTTON_BG_COLOR_LIGHTS_HOVER\fP = '#1A237E'"
.br
.ti -1c
.RI "string \fBBUTTON_FONT_COLOR_LIGHTS\fP = '#FFFFFF'"
.br
.ti -1c
.RI "string \fBBUTTON_FONT_COLOR_LIGHTS_HOVER\fP = '#FFFFFF'"
.br
.ti -1c
.RI "string \fBBUTTON_BG_COLOR_SENSORS\fP = '#3F51B5'"
.br
.ti -1c
.RI "string \fBBUTTON_FONT_COLOR_SENSORS\fP = '#FFFFFF'"
.br
.ti -1c
.RI "string \fBBUTTON_BG_COLOR_SENSORS_HOVER\fP = '#1A237E'"
.br
.ti -1c
.RI "string \fBBUTTON_FONT_COLOR_SENSORS_HOVER\fP = '#FFFFFF'"
.br
.ti -1c
.RI "string \fBBUTTON_BG_COLOR_CONFIGURE\fP = '#2196f3'"
.br
.ti -1c
.RI "string \fBBUTTON_FONT_COLOR_CONFIGURE\fP = '#FFFFFF'"
.br
.ti -1c
.RI "string \fBBUTTON_BG_COLOR_CONFIGURE_HOVER\fP = '#0d47a1'"
.br
.ti -1c
.RI "string \fBBUTTON_FONT_COLOR_CONFIGURE_HOVER\fP = '#FFFFFF'"
.br
.ti -1c
.RI "string \fBBUTTON_BG_COLOR_SYSTEM\fP = '#2196f3'"
.br
.ti -1c
.RI "string \fBBUTTON_FONT_COLOR_SYSTEM\fP = '#FFFFFF'"
.br
.ti -1c
.RI "string \fBBUTTON_BG_COLOR_SYSTEM_HOVER\fP = '#0d47a1'"
.br
.ti -1c
.RI "string \fBBUTTON_FONT_COLOR_SYSTEM_HOVER\fP = '#FFFFFF'"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "string DesignColors\&.APP_BAR = '#212121'"

.SS "string DesignColors\&.APP_BG = '#303030'"

.SS "string DesignColors\&.APP_DIALOG = '#424242'"

.SS "string DesignColors\&.APP_FONT_COLOR = '#ffffff'"

.SS "string DesignColors\&.BUTTON_BG_COLOR_ACTIVE = '#3f51b5'"

.SS "string DesignColors\&.BUTTON_BG_COLOR_CONFIGURE = '#2196f3'"

.SS "string DesignColors\&.BUTTON_BG_COLOR_CONFIGURE_HOVER = '#0d47a1'"

.SS "DesignColors\&.BUTTON_BG_COLOR_HOVER = \fBAPP_BG\fP"

.SS "DesignColors\&.BUTTON_BG_COLOR_INACTIVE = \fBAPP_BG\fP"

.SS "string DesignColors\&.BUTTON_BG_COLOR_LIGHTS = '#3F51B5'"

.SS "string DesignColors\&.BUTTON_BG_COLOR_LIGHTS_HOVER = '#1A237E'"

.SS "DesignColors\&.BUTTON_BG_COLOR_NORMAL = \fBAPP_BG\fP"

.SS "string DesignColors\&.BUTTON_BG_COLOR_SENSORS = '#3F51B5'"

.SS "string DesignColors\&.BUTTON_BG_COLOR_SENSORS_HOVER = '#1A237E'"

.SS "string DesignColors\&.BUTTON_BG_COLOR_SYSTEM = '#2196f3'"

.SS "string DesignColors\&.BUTTON_BG_COLOR_SYSTEM_HOVER = '#0d47a1'"

.SS "string DesignColors\&.BUTTON_FONT_COLOR = '#FFFFFF'"

.SS "string DesignColors\&.BUTTON_FONT_COLOR_CONFIGURE = '#FFFFFF'"

.SS "string DesignColors\&.BUTTON_FONT_COLOR_CONFIGURE_HOVER = '#FFFFFF'"

.SS "DesignColors\&.BUTTON_FONT_COLOR_HOVER_ACTIVE = \fBAPP_BG\fP"

.SS "string DesignColors\&.BUTTON_FONT_COLOR_HOVER_INACTIVE = '#3f51b5'"

.SS "string DesignColors\&.BUTTON_FONT_COLOR_LIGHTS = '#FFFFFF'"

.SS "string DesignColors\&.BUTTON_FONT_COLOR_LIGHTS_HOVER = '#FFFFFF'"

.SS "string DesignColors\&.BUTTON_FONT_COLOR_SENSORS = '#FFFFFF'"

.SS "string DesignColors\&.BUTTON_FONT_COLOR_SENSORS_HOVER = '#FFFFFF'"

.SS "string DesignColors\&.BUTTON_FONT_COLOR_SYSTEM = '#FFFFFF'"

.SS "string DesignColors\&.BUTTON_FONT_COLOR_SYSTEM_HOVER = '#FFFFFF'"

.SH "Author"
.PP 
Generated automatically by Doxygen for SensorNode from the source code\&.
