.TH "findmyphone" 3 "Mon Apr 3 2017" "Version 0.2" "SensorNode" \" -*- nroff -*-
.ad l
.nh
.SH NAME
findmyphone \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBtarget_name\fP = 'MinxSensorNode01'"
.br
.ti -1c
.RI "\fBtarget_address\fP = None"
.br
.ti -1c
.RI "\fBnearby_devices\fP = bluetooth\&.discover_devices()"
.br
.ti -1c
.RI "\fBt\fP = bluetooth\&.lookup_name( bdaddr,20 )"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "findmyphone\&.nearby_devices = bluetooth\&.discover_devices()"

.SS "findmyphone\&.t = bluetooth\&.lookup_name( bdaddr,20 )"

.SS "findmyphone\&.target_address = None"

.SS "string findmyphone\&.target_name = 'MinxSensorNode01'"

.SH "Author"
.PP 
Generated automatically by Doxygen for SensorNode from the source code\&.
