.TH "src/IO/I2C.cpp" 3 "Thu May 25 2017" "Version 0.2" "SensorNode" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/IO/I2C.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <avr/io\&.h>\fP
.br
\fC#include <util/twi\&.h>\fP
.br
\fC#include 'I2C\&.hpp'\fP
.br

.SH "Detailed Description"
.PP 
Project: \fBSensorNode\fP
.PP
\fBI2C\&.cpp\fP
.PP
Created on: 28 Apr 2017
.PP
Author: matthias
.PP
Revision:
.PP
License: 
.SH "Author"
.PP 
Generated automatically by Doxygen for SensorNode from the source code\&.
