.TH "src/IO/IO.cpp" 3 "Thu May 25 2017" "Version 0.2" "SensorNode" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/IO/IO.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'IO\&.hpp'\fP
.br
\fC#include 'I2C\&.hpp'\fP
.br
\fC#include 'USART\&.h'\fP
.br
\fC#include 'SPI\&.h'\fP
.br

.SH "Detailed Description"
.PP 
Project: \fBSensorNode\fP
.PP
\fBIO\&.cpp\fP
.PP
Created on: 25 May 2017
.PP
Author: matthias
.PP
Revision:
.PP
License: 
.SH "Author"
.PP 
Generated automatically by Doxygen for SensorNode from the source code\&.
