.TH "src/IO/IO.h" 3 "Thu May 25 2017" "Version 0.2" "SensorNode" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/IO/IO.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'I2C\&.hpp'\fP
.br
\fC#include 'USART\&.h'\fP
.br
\fC#include 'SPI\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBIO\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Project: \fBSensorNode\fP
.PP
IO\&.hpp
.PP
Created on: 25 May 2017
.PP
Author: Matthias Minx
.PP
Revision: 1
.PP
License: 
.SH "Author"
.PP 
Generated automatically by Doxygen for SensorNode from the source code\&.
