.TH "Python/old/Protocol/NodeProtocol.py" 3 "Mon Apr 3 2017" "Version 0.2" "SensorNode" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Python/old/Protocol/NodeProtocol.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBProtocol\&.NodeProtocol\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBProtocol\&.NodeProtocol\&.DHT22\fP ()"
.br
.ti -1c
.RI "def \fBProtocol\&.NodeProtocol\&.ReadSensorDS18B20\fP (tt, MAC)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SensorNode from the source code\&.
