.TH "NodeProtocol" 3 "Mon Apr 3 2017" "Version 0.2" "SensorNode" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NodeProtocol \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBNPSetBluetoothName\fP (name)"
.br
.ti -1c
.RI "def \fBNPSetBluetoothPIN\fP (pin)"
.br
.ti -1c
.RI "def \fBNPSetNRFPipe\fP (pipeNr, mac)"
.br
.ti -1c
.RI "def \fBNPSetNRFPipeEnable\fP (pipeNr)"
.br
.ti -1c
.RI "def \fBNPSetNRFChannel\fP (chN)"
.br
.ti -1c
.RI "def \fBNPSetNRFPowerLevel\fP (pwrlvl)"
.br
.ti -1c
.RI "def \fBNPSetNRFDataRate\fP (datart)"
.br
.ti -1c
.RI "def \fBNPSetNRFCRCLevel\fP (crclvl)"
.br
.ti -1c
.RI "def \fBNPSetNRFPayLoadSize\fP (payloadsze)"
.br
.ti -1c
.RI "def \fBNPSetNRFAutoACK\fP (endisack)"
.br
.ti -1c
.RI "def \fBNPSetNRFResetModule\fP ()"
.br
.ti -1c
.RI "def \fBNPGetNRGConfig\fP ()"
.br
.ti -1c
.RI "def \fBNPGetSensorDataTempDHT22\fP ()"
.br
.ti -1c
.RI "def \fBNPGetSensorDataHumidityDHT22\fP ()"
.br
.ti -1c
.RI "def \fBNPGetSensorDataTempHumidityDHT22\fP ()"
.br
.ti -1c
.RI "def \fBNPGetSensorDataLightsense\fP ()"
.br
.ti -1c
.RI "def \fBNPGetSensorDataTempDS18B20\fP ()"
.br
.ti -1c
.RI "def \fBNPGetSensorDataMove\fP ()"
.br
.ti -1c
.RI "def \fBNPGetSensorDataRemote\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def NodeProtocol\&.NPGetNRGConfig ()"

.SS "def NodeProtocol\&.NPGetSensorDataHumidityDHT22 ()"

.SS "def NodeProtocol\&.NPGetSensorDataLightsense ()"

.SS "def NodeProtocol\&.NPGetSensorDataMove ()"

.SS "def NodeProtocol\&.NPGetSensorDataRemote ()"

.SS "def NodeProtocol\&.NPGetSensorDataTempDHT22 ()"

.SS "def NodeProtocol\&.NPGetSensorDataTempDS18B20 ()"

.SS "def NodeProtocol\&.NPGetSensorDataTempHumidityDHT22 ()"

.SS "def NodeProtocol\&.NPSetBluetoothName ( name)"

.SS "def NodeProtocol\&.NPSetBluetoothPIN ( pin)"

.SS "def NodeProtocol\&.NPSetNRFAutoACK ( endisack)"

.SS "def NodeProtocol\&.NPSetNRFChannel ( chN)"

.SS "def NodeProtocol\&.NPSetNRFCRCLevel ( crclvl)"

.SS "def NodeProtocol\&.NPSetNRFDataRate ( datart)"

.SS "def NodeProtocol\&.NPSetNRFPayLoadSize ( payloadsze)"

.SS "def NodeProtocol\&.NPSetNRFPipe ( pipeNr,  mac)"

.SS "def NodeProtocol\&.NPSetNRFPipeEnable ( pipeNr)"

.SS "def NodeProtocol\&.NPSetNRFPowerLevel ( pwrlvl)"

.SS "def NodeProtocol\&.NPSetNRFResetModule ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for SensorNode from the source code\&.
