.TH "src/Wireless/NRF24L01registers.h" 3 "Mon Apr 3 2017" "Version 0.2" "SensorNode" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Wireless/NRF24L01registers.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBNRF24L01_REG_CONFIG\fP   0x00"
.br
.ti -1c
.RI "#define \fBNRF24L01_REG_EN_AA\fP   0x01"
.br
.ti -1c
.RI "#define \fBNRF24L01_REG_EN_RXADDR\fP   0x02"
.br
.ti -1c
.RI "#define \fBNRF24L01_REG_SETUP_AW\fP   0x03"
.br
.ti -1c
.RI "#define \fBNRF24L01_REG_SETUP_RETR\fP   0x04"
.br
.ti -1c
.RI "#define \fBNRF24L01_REG_RF_CH\fP   0x05"
.br
.ti -1c
.RI "#define \fBNRF24L01_REG_RF_SETUP\fP   0x06"
.br
.ti -1c
.RI "#define \fBNRF24L01_REG_STATUS\fP   0x07"
.br
.ti -1c
.RI "#define \fBNRF24L01_REG_OBSERVE_TX\fP   0x08"
.br
.ti -1c
.RI "#define \fBNRF24L01_REG_CD\fP   0x09"
.br
.ti -1c
.RI "#define \fBNRF24L01_REG_RX_ADDR_P0\fP   0x0A"
.br
.ti -1c
.RI "#define \fBNRF24L01_REG_RX_ADDR_P1\fP   0x0B"
.br
.ti -1c
.RI "#define \fBNRF24L01_REG_RX_ADDR_P2\fP   0x0C"
.br
.ti -1c
.RI "#define \fBNRF24L01_REG_RX_ADDR_P3\fP   0x0D"
.br
.ti -1c
.RI "#define \fBNRF24L01_REG_RX_ADDR_P4\fP   0x0E"
.br
.ti -1c
.RI "#define \fBNRF24L01_REG_RX_ADDR_P5\fP   0x0F"
.br
.ti -1c
.RI "#define \fBNRF24L01_REG_TX_ADDR\fP   0x10"
.br
.ti -1c
.RI "#define \fBNRF24L01_REG_RX_PW_P0\fP   0x11"
.br
.ti -1c
.RI "#define \fBNRF24L01_REG_RX_PW_P1\fP   0x12"
.br
.ti -1c
.RI "#define \fBNRF24L01_REG_RX_PW_P2\fP   0x13"
.br
.ti -1c
.RI "#define \fBNRF24L01_REG_RX_PW_P3\fP   0x14"
.br
.ti -1c
.RI "#define \fBNRF24L01_REG_RX_PW_P4\fP   0x15"
.br
.ti -1c
.RI "#define \fBNRF24L01_REG_RX_PW_P5\fP   0x16"
.br
.ti -1c
.RI "#define \fBNRF24L01_REG_FIFO_STATUS\fP   0x17"
.br
.ti -1c
.RI "#define \fBNRF24L01_REG_FEATURE\fP   0x1D"
.br
.ti -1c
.RI "#define \fBNRF24L01_REG_DYNPD\fP   0x1C"
.br
.ti -1c
.RI "#define \fBNRF24L01_REG_MASK_RX_DR\fP   6"
.br
.ti -1c
.RI "#define \fBNRF24L01_REG_MASK_TX_DS\fP   5"
.br
.ti -1c
.RI "#define \fBNRF24L01_REG_MASK_MAX_RT\fP   4"
.br
.ti -1c
.RI "#define \fBNRF24L01_REG_EN_CRC\fP   3"
.br
.ti -1c
.RI "#define \fBNRF24L01_REG_CRCO\fP   2"
.br
.ti -1c
.RI "#define \fBNRF24L01_REG_PWR_UP\fP   1"
.br
.ti -1c
.RI "#define \fBNRF24L01_REG_PRIM_RX\fP   0"
.br
.ti -1c
.RI "#define \fBNRF24L01_REG_ENAA_P5\fP   5"
.br
.ti -1c
.RI "#define \fBNRF24L01_REG_ENAA_P4\fP   4"
.br
.ti -1c
.RI "#define \fBNRF24L01_REG_ENAA_P3\fP   3"
.br
.ti -1c
.RI "#define \fBNRF24L01_REG_ENAA_P2\fP   2"
.br
.ti -1c
.RI "#define \fBNRF24L01_REG_ENAA_P1\fP   1"
.br
.ti -1c
.RI "#define \fBNRF24L01_REG_ENAA_P0\fP   0"
.br
.ti -1c
.RI "#define \fBNRF24L01_REG_ERX_P5\fP   5"
.br
.ti -1c
.RI "#define \fBNRF24L01_REG_ERX_P4\fP   4"
.br
.ti -1c
.RI "#define \fBNRF24L01_REG_ERX_P3\fP   3"
.br
.ti -1c
.RI "#define \fBNRF24L01_REG_ERX_P2\fP   2"
.br
.ti -1c
.RI "#define \fBNRF24L01_REG_ERX_P1\fP   1"
.br
.ti -1c
.RI "#define \fBNRF24L01_REG_ERX_P0\fP   0"
.br
.ti -1c
.RI "#define \fBNRF24L01_REG_AW\fP   0"
.br
.ti -1c
.RI "#define \fBNRF24L01_REG_ARD\fP   4"
.br
.ti -1c
.RI "#define \fBNRF24L01_REG_ARC\fP   0"
.br
.ti -1c
.RI "#define \fBNRF24L01_REG_PLL_LOCK\fP   4"
.br
.ti -1c
.RI "#define \fBNRF24L01_REG_RF_DR\fP   3"
.br
.ti -1c
.RI "#define \fBNRF24L01_REG_RF_PWR\fP   1"
.br
.ti -1c
.RI "#define \fBNRF24L01_REG_LNA_HCURR\fP   0"
.br
.ti -1c
.RI "#define \fBNRF24L01_REG_RX_DR\fP   6"
.br
.ti -1c
.RI "#define \fBNRF24L01_REG_TX_DS\fP   5"
.br
.ti -1c
.RI "#define \fBNRF24L01_REG_MAX_RT\fP   4"
.br
.ti -1c
.RI "#define \fBNRF24L01_REG_RX_P_NO\fP   1"
.br
.ti -1c
.RI "#define \fBNRF24L01_REG_TX_FULL\fP   0"
.br
.ti -1c
.RI "#define \fBNRF24L01_REG_PLOS_CNT\fP   4"
.br
.ti -1c
.RI "#define \fBNRF24L01_REG_ARC_CNT\fP   0"
.br
.ti -1c
.RI "#define \fBNRF24L01_REG_TX_REUSE\fP   6"
.br
.ti -1c
.RI "#define \fBNRF24L01_REG_FIFO_FULL\fP   5"
.br
.ti -1c
.RI "#define \fBNRF24L01_REG_TX_EMPTY\fP   4"
.br
.ti -1c
.RI "#define \fBNRF24L01_REG_RX_FULL\fP   1"
.br
.ti -1c
.RI "#define \fBNRF24L01_REG_RX_EMPTY\fP   0"
.br
.ti -1c
.RI "#define \fBNRF24L01_REG_RPD\fP   0x09"
.br
.ti -1c
.RI "#define \fBNRF24L01_REG_DPL_P5\fP   5"
.br
.ti -1c
.RI "#define \fBNRF24L01_REG_DPL_P4\fP   4"
.br
.ti -1c
.RI "#define \fBNRF24L01_REG_DPL_P3\fP   3"
.br
.ti -1c
.RI "#define \fBNRF24L01_REG_DPL_P2\fP   2"
.br
.ti -1c
.RI "#define \fBNRF24L01_REG_DPL_P1\fP   1"
.br
.ti -1c
.RI "#define \fBNRF24L01_REG_DPL_P0\fP   0"
.br
.ti -1c
.RI "#define \fBNRF24L01_REG_EN_DPL\fP   2"
.br
.ti -1c
.RI "#define \fBNRF24L01_REG_EN_ACK_PAY\fP   1"
.br
.ti -1c
.RI "#define \fBNRF24L01_REG_EN_DYN_ACK\fP   0"
.br
.ti -1c
.RI "#define \fBNRF24L01_REG_RF_DR_LOW\fP   5"
.br
.ti -1c
.RI "#define \fBNRF24L01_REG_RF_DR_HIGH\fP   3"
.br
.ti -1c
.RI "#define \fBNRF24L01_REG_RF_PWR_LOW\fP   1"
.br
.ti -1c
.RI "#define \fBNRF24L01_REG_RF_PWR_HIGH\fP   2"
.br
.ti -1c
.RI "#define \fBNRF24L01_CMD_R_REGISTER\fP   0x00"
.br
.ti -1c
.RI "#define \fBNRF24L01_CMD_W_REGISTER\fP   0x20"
.br
.ti -1c
.RI "#define \fBNRF24L01_CMD_REGISTER_MASK\fP   0x1F"
.br
.ti -1c
.RI "#define \fBNRF24L01_CMD_ACTIVATE\fP   0x50"
.br
.ti -1c
.RI "#define \fBNRF24L01_CMD_R_RX_PL_WID\fP   0x60"
.br
.ti -1c
.RI "#define \fBNRF24L01_CMD_R_RX_PAYLOAD\fP   0x61"
.br
.ti -1c
.RI "#define \fBNRF24L01_CMD_W_TX_PAYLOAD\fP   0xA0"
.br
.ti -1c
.RI "#define \fBNRF24L01_CMD_W_ACK_PAYLOAD\fP   0xA8"
.br
.ti -1c
.RI "#define \fBNRF24L01_CMD_FLUSH_TX\fP   0xE1"
.br
.ti -1c
.RI "#define \fBNRF24L01_CMD_FLUSH_RX\fP   0xE2"
.br
.ti -1c
.RI "#define \fBNRF24L01_CMD_REUSE_TX_PL\fP   0xE3"
.br
.ti -1c
.RI "#define \fBNRF24L01_CMD_NOP\fP   0xFF"
.br
.ti -1c
.RI "#define \fBRPD\fP   0x09"
.br
.ti -1c
.RI "#define \fBNRF24L01_CMD_W_TX_PAYLOAD_NO_ACK\fP   0xB0"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define NRF24L01_CMD_ACTIVATE   0x50"

.SS "#define NRF24L01_CMD_FLUSH_RX   0xE2"

.SS "#define NRF24L01_CMD_FLUSH_TX   0xE1"

.SS "#define NRF24L01_CMD_NOP   0xFF"

.SS "#define NRF24L01_CMD_R_REGISTER   0x00"

.SS "#define NRF24L01_CMD_R_RX_PAYLOAD   0x61"

.SS "#define NRF24L01_CMD_R_RX_PL_WID   0x60"

.SS "#define NRF24L01_CMD_REGISTER_MASK   0x1F"

.SS "#define NRF24L01_CMD_REUSE_TX_PL   0xE3"

.SS "#define NRF24L01_CMD_W_ACK_PAYLOAD   0xA8"

.SS "#define NRF24L01_CMD_W_REGISTER   0x20"

.SS "#define NRF24L01_CMD_W_TX_PAYLOAD   0xA0"

.SS "#define NRF24L01_CMD_W_TX_PAYLOAD_NO_ACK   0xB0"

.SS "#define NRF24L01_REG_ARC   0"

.SS "#define NRF24L01_REG_ARC_CNT   0"

.SS "#define NRF24L01_REG_ARD   4"

.SS "#define NRF24L01_REG_AW   0"

.SS "#define NRF24L01_REG_CD   0x09"

.SS "#define NRF24L01_REG_CONFIG   0x00"

.SS "#define NRF24L01_REG_CRCO   2"

.SS "#define NRF24L01_REG_DPL_P0   0"

.SS "#define NRF24L01_REG_DPL_P1   1"

.SS "#define NRF24L01_REG_DPL_P2   2"

.SS "#define NRF24L01_REG_DPL_P3   3"

.SS "#define NRF24L01_REG_DPL_P4   4"

.SS "#define NRF24L01_REG_DPL_P5   5"

.SS "#define NRF24L01_REG_DYNPD   0x1C"

.SS "#define NRF24L01_REG_EN_AA   0x01"

.SS "#define NRF24L01_REG_EN_ACK_PAY   1"

.SS "#define NRF24L01_REG_EN_CRC   3"

.SS "#define NRF24L01_REG_EN_DPL   2"

.SS "#define NRF24L01_REG_EN_DYN_ACK   0"

.SS "#define NRF24L01_REG_EN_RXADDR   0x02"

.SS "#define NRF24L01_REG_ENAA_P0   0"

.SS "#define NRF24L01_REG_ENAA_P1   1"

.SS "#define NRF24L01_REG_ENAA_P2   2"

.SS "#define NRF24L01_REG_ENAA_P3   3"

.SS "#define NRF24L01_REG_ENAA_P4   4"

.SS "#define NRF24L01_REG_ENAA_P5   5"

.SS "#define NRF24L01_REG_ERX_P0   0"

.SS "#define NRF24L01_REG_ERX_P1   1"

.SS "#define NRF24L01_REG_ERX_P2   2"

.SS "#define NRF24L01_REG_ERX_P3   3"

.SS "#define NRF24L01_REG_ERX_P4   4"

.SS "#define NRF24L01_REG_ERX_P5   5"

.SS "#define NRF24L01_REG_FEATURE   0x1D"

.SS "#define NRF24L01_REG_FIFO_FULL   5"

.SS "#define NRF24L01_REG_FIFO_STATUS   0x17"

.SS "#define NRF24L01_REG_LNA_HCURR   0"

.SS "#define NRF24L01_REG_MASK_MAX_RT   4"

.SS "#define NRF24L01_REG_MASK_RX_DR   6"

.SS "#define NRF24L01_REG_MASK_TX_DS   5"

.SS "#define NRF24L01_REG_MAX_RT   4"

.SS "#define NRF24L01_REG_OBSERVE_TX   0x08"

.SS "#define NRF24L01_REG_PLL_LOCK   4"

.SS "#define NRF24L01_REG_PLOS_CNT   4"

.SS "#define NRF24L01_REG_PRIM_RX   0"

.SS "#define NRF24L01_REG_PWR_UP   1"

.SS "#define NRF24L01_REG_RF_CH   0x05"

.SS "#define NRF24L01_REG_RF_DR   3"

.SS "#define NRF24L01_REG_RF_DR_HIGH   3"

.SS "#define NRF24L01_REG_RF_DR_LOW   5"

.SS "#define NRF24L01_REG_RF_PWR   1"

.SS "#define NRF24L01_REG_RF_PWR_HIGH   2"

.SS "#define NRF24L01_REG_RF_PWR_LOW   1"

.SS "#define NRF24L01_REG_RF_SETUP   0x06"

.SS "#define NRF24L01_REG_RPD   0x09"

.SS "#define NRF24L01_REG_RX_ADDR_P0   0x0A"

.SS "#define NRF24L01_REG_RX_ADDR_P1   0x0B"

.SS "#define NRF24L01_REG_RX_ADDR_P2   0x0C"

.SS "#define NRF24L01_REG_RX_ADDR_P3   0x0D"

.SS "#define NRF24L01_REG_RX_ADDR_P4   0x0E"

.SS "#define NRF24L01_REG_RX_ADDR_P5   0x0F"

.SS "#define NRF24L01_REG_RX_DR   6"

.SS "#define NRF24L01_REG_RX_EMPTY   0"

.SS "#define NRF24L01_REG_RX_FULL   1"

.SS "#define NRF24L01_REG_RX_P_NO   1"

.SS "#define NRF24L01_REG_RX_PW_P0   0x11"

.SS "#define NRF24L01_REG_RX_PW_P1   0x12"

.SS "#define NRF24L01_REG_RX_PW_P2   0x13"

.SS "#define NRF24L01_REG_RX_PW_P3   0x14"

.SS "#define NRF24L01_REG_RX_PW_P4   0x15"

.SS "#define NRF24L01_REG_RX_PW_P5   0x16"

.SS "#define NRF24L01_REG_SETUP_AW   0x03"

.SS "#define NRF24L01_REG_SETUP_RETR   0x04"

.SS "#define NRF24L01_REG_STATUS   0x07"

.SS "#define NRF24L01_REG_TX_ADDR   0x10"

.SS "#define NRF24L01_REG_TX_DS   5"

.SS "#define NRF24L01_REG_TX_EMPTY   4"

.SS "#define NRF24L01_REG_TX_FULL   0"

.SS "#define NRF24L01_REG_TX_REUSE   6"

.SS "#define RPD   0x09"

.SH "Author"
.PP 
Generated automatically by Doxygen for SensorNode from the source code\&.
