.TH "openhab.OpenHab" 3 "Thu May 25 2017" "Version 0.2" "SensorNode" \" -*- nroff -*-
.ad l
.nh
.SH NAME
openhab.OpenHab \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, hst)"
.br
.ti -1c
.RI "def \fBcheckAllItemsExist\fP (self)"
.br
.ti -1c
.RI "def \fBputDataInItem\fP (self, data, itemName)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBhost\fP"
.br
.ti -1c
.RI "\fBhttps_sslv3_handler\fP"
.br
.ti -1c
.RI "\fBopener\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def openhab\&.OpenHab\&.__init__ ( self,  hst)"

.PP
.nf
Initialize Openhab Class 
.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "def openhab\&.OpenHab\&.checkAllItemsExist ( self)"

.SS "def openhab\&.OpenHab\&.putDataInItem ( self,  data,  itemName)"

.PP
.nf
Put data to openhab item 
.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "openhab\&.OpenHab\&.host"

.SS "openhab\&.OpenHab\&.https_sslv3_handler"

.SS "openhab\&.OpenHab\&.opener"


.SH "Author"
.PP 
Generated automatically by Doxygen for SensorNode from the source code\&.
