.TH "src/Sensors/Photoresistor.cpp" 3 "Tue Apr 4 2017" "Version 0.2" "SensorNode" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Sensors/Photoresistor.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Photoresistor\&.h'\fP
.br
\fC#include <avr/io\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br

.SH "Detailed Description"
.PP 
Project: \fBSensorNode\fP
.PP
\fBPhotoresistor\&.cpp\fP
.PP
Created on: Nov 12, 2016
.PP
Author: Matthias Minx
.PP
Revision: 0\&.2 
.SH "Author"
.PP 
Generated automatically by Doxygen for SensorNode from the source code\&.
