.TH "src/Sensors/Photoresistor.h" 3 "Thu May 25 2017" "Version 0.2" "SensorNode" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Sensors/Photoresistor.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <avr/io\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSensors::Photoresistor\fP"
.br
.RI "\fI\fBPhotoresistor\fP class definition\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBSensors\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Project: \fBSensorNode\fP
.PP
\fBPhotoresistor\&.h\fP
.PP
Created on: Nov 12, 2016
.PP
Author: Matthias Minx
.PP
Revision: 0\&.2 
.SH "Author"
.PP 
Generated automatically by Doxygen for SensorNode from the source code\&.
