.TH "Protocol.readSerial" 3 "Mon Apr 3 2017" "Version 0.2" "SensorNode" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Protocol.readSerial \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBNewSerialCon\fP (port, baudrate)"
.br
.ti -1c
.RI "def \fBReadData\fP (ser, queryStr)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def Protocol\&.readSerial\&.NewSerialCon ( port,  baudrate)"

.SS "def Protocol\&.readSerial\&.ReadData ( ser,  queryStr)"

.SH "Author"
.PP 
Generated automatically by Doxygen for SensorNode from the source code\&.
