.TH "Protocol.NodeProtocol" 3 "Mon Apr 3 2017" "Version 0.2" "SensorNode" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Protocol.NodeProtocol \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBDHT22\fP ()"
.br
.ti -1c
.RI "def \fBReadSensorDS18B20\fP (tt, MAC)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def Protocol\&.NodeProtocol\&.DHT22 ()"

.SS "def Protocol\&.NodeProtocol\&.ReadSensorDS18B20 ( tt,  MAC)"

.SH "Author"
.PP 
Generated automatically by Doxygen for SensorNode from the source code\&.
