.TH "ReadSensor.SerialConnection.SerialConnection" 3 "Mon Apr 3 2017" "Version 0.2" "SensorNode" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ReadSensor.SerialConnection.SerialConnection \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, port, baudrate)"
.br
.ti -1c
.RI "def \fBReadData\fP (self, queryStr)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBser\fP"
.br
.ti -1c
.RI "\fBerr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Sets up a serial connection
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def ReadSensor\&.SerialConnection\&.SerialConnection\&.__init__ ( self,  port,  baudrate)"

.SH "Member Function Documentation"
.PP 
.SS "def ReadSensor\&.SerialConnection\&.SerialConnection\&.ReadData ( self,  queryStr)"

.SH "Member Data Documentation"
.PP 
.SS "ReadSensor\&.SerialConnection\&.SerialConnection\&.err"

.SS "ReadSensor\&.SerialConnection\&.SerialConnection\&.ser"


.SH "Author"
.PP 
Generated automatically by Doxygen for SensorNode from the source code\&.
