.TH "ReadSensor.Sensors.Sensors.DS18B20" 3 "Mon Apr 3 2017" "Version 0.2" "SensorNode" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ReadSensor.Sensors.Sensors.DS18B20 \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, responseStr, sensStr)"
.br
.ti -1c
.RI "def \fBGetValuePair\fP (self, idx)"
.br
.ti -1c
.RI "def \fBGetAvgTemperature\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBMAC\fP"
.br
.ti -1c
.RI "\fBT\fP"
.br
.ti -1c
.RI "\fBunitT\fP"
.br
.ti -1c
.RI "\fBds\fP"
.br
.ti -1c
.RI "\fBnumEl\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def ReadSensor\&.Sensors\&.Sensors\&.DS18B20\&.__init__ ( self,  responseStr,  sensStr)"

.SH "Member Function Documentation"
.PP 
.SS "def ReadSensor\&.Sensors\&.Sensors\&.DS18B20\&.GetAvgTemperature ( self)"

.SS "def ReadSensor\&.Sensors\&.Sensors\&.DS18B20\&.GetValuePair ( self,  idx)"

.SH "Member Data Documentation"
.PP 
.SS "ReadSensor\&.Sensors\&.Sensors\&.DS18B20\&.ds"

.SS "ReadSensor\&.Sensors\&.Sensors\&.DS18B20\&.MAC"

.SS "ReadSensor\&.Sensors\&.Sensors\&.DS18B20\&.numEl"

.SS "ReadSensor\&.Sensors\&.Sensors\&.DS18B20\&.T"

.SS "ReadSensor\&.Sensors\&.Sensors\&.DS18B20\&.unitT"


.SH "Author"
.PP 
Generated automatically by Doxygen for SensorNode from the source code\&.
