.TH "ReadSensor.Sensors.Sensors.LightDigital" 3 "Mon Apr 3 2017" "Version 0.2" "SensorNode" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ReadSensor.Sensors.Sensors.LightDigital \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, responseStr, sensStr)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBvalue\fP"
.br
.ti -1c
.RI "\fBld\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def ReadSensor\&.Sensors\&.Sensors\&.LightDigital\&.__init__ ( self,  responseStr,  sensStr)"

.SH "Member Data Documentation"
.PP 
.SS "ReadSensor\&.Sensors\&.Sensors\&.LightDigital\&.ld"

.SS "ReadSensor\&.Sensors\&.Sensors\&.LightDigital\&.value"


.SH "Author"
.PP 
Generated automatically by Doxygen for SensorNode from the source code\&.
