.TH "ReadSensor.Sensors.Sensors.Sensors" 3 "Mon Apr 3 2017" "Version 0.2" "SensorNode" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ReadSensor.Sensors.Sensors.Sensors \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, responsrStr, sensStr)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBsens\fP"
.br
.ti -1c
.RI "\fBs\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def ReadSensor\&.Sensors\&.Sensors\&.Sensors\&.__init__ ( self,  responsrStr,  sensStr)"

.SH "Member Data Documentation"
.PP 
.SS "ReadSensor\&.Sensors\&.Sensors\&.Sensors\&.s"

.SS "ReadSensor\&.Sensors\&.Sensors\&.Sensors\&.sens"


.SH "Author"
.PP 
Generated automatically by Doxygen for SensorNode from the source code\&.
