.TH "Python/old/Protocol/readSerial.py" 3 "Mon Apr 3 2017" "Version 0.2" "SensorNode" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Python/old/Protocol/readSerial.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBProtocol\&.readSerial\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBProtocol\&.readSerial\&.NewSerialCon\fP (port, baudrate)"
.br
.ti -1c
.RI "def \fBProtocol\&.readSerial\&.ReadData\fP (ser, queryStr)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SensorNode from the source code\&.
