.TH "ReadSensor.Sensors.Sensors.DHT22" 3 "Mon Apr 3 2017" "Version 0.2" "SensorNode" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ReadSensor.Sensors.Sensors.DHT22 \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, responseStr, sensStr)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBH\fP"
.br
.ti -1c
.RI "\fBunitH\fP"
.br
.ti -1c
.RI "\fBT\fP"
.br
.ti -1c
.RI "\fBunitT\fP"
.br
.ti -1c
.RI "\fBerr\fP"
.br
.ti -1c
.RI "\fBdht\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def ReadSensor\&.Sensors\&.Sensors\&.DHT22\&.__init__ ( self,  responseStr,  sensStr)"

.SH "Member Data Documentation"
.PP 
.SS "ReadSensor\&.Sensors\&.Sensors\&.DHT22\&.dht"

.SS "ReadSensor\&.Sensors\&.Sensors\&.DHT22\&.err"

.SS "ReadSensor\&.Sensors\&.Sensors\&.DHT22\&.H"

.SS "ReadSensor\&.Sensors\&.Sensors\&.DHT22\&.T"

.SS "ReadSensor\&.Sensors\&.Sensors\&.DHT22\&.unitH"

.SS "ReadSensor\&.Sensors\&.Sensors\&.DHT22\&.unitT"


.SH "Author"
.PP 
Generated automatically by Doxygen for SensorNode from the source code\&.
