.TH "src/Sensors/Sensors.hpp" 3 "Thu May 25 2017" "Version 0.2" "SensorNode" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Sensors/Sensors.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'DHT22\&.h'\fP
.br
\fC#include 'DS18B20\&.h'\fP
.br
\fC#include 'Photoresistor\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSensors::Sensors\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBSensors\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Project: \fBSensorNode\fP
.PP
\fBSensors\&.hpp\fP
.PP
Created on: 25 May 2017
.PP
Author: Matthias Minx
.PP
Revision: 1
.PP
License: 
.SH "Author"
.PP 
Generated automatically by Doxygen for SensorNode from the source code\&.
