.TH "SensorNode.SensorNode" 3 "Tue Apr 4 2017" "Version 0.2" "SensorNode" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SensorNode.SensorNode \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBUpdateThreads\fP (self, sensorObj)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBthreadLock\fP = thread\&.allocate_lock()"
.br
.ti -1c
.RI "list \fBnodeAddresses\fP = ['A0:A0:A0:A0:A0']"
.br
.ti -1c
.RI "string \fBport\fP = '/dev/ttyAMA0'"
.br
.ti -1c
.RI "int \fBbaudrate\fP = 9600"
.br
.ti -1c
.RI "\fBsens\fP = \fBsensors\&.Sensors\fP(\fBport\fP, \fBbaudrate\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
SensorNode class:

    main code to execute
.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "def SensorNode\&.SensorNode\&.UpdateThreads ( self,  sensorObj)"

.PP
.nf

.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "int SensorNode\&.SensorNode\&.baudrate = 9600\fC [static]\fP"

.SS "list SensorNode\&.SensorNode\&.nodeAddresses = ['A0:A0:A0:A0:A0']\fC [static]\fP"

.SS "string SensorNode\&.SensorNode\&.port = '/dev/ttyAMA0'\fC [static]\fP"

.SS "SensorNode\&.SensorNode\&.sens = \fBsensors\&.Sensors\fP(\fBport\fP, \fBbaudrate\fP)\fC [static]\fP"

.SS "SensorNode\&.SensorNode\&.threadLock = thread\&.allocate_lock()\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for SensorNode from the source code\&.
