.TH "sensors.DHT22" 3 "Thu May 25 2017" "Version 0.2" "SensorNode" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sensors.DHT22 \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBreadsensor\&.ReadSensor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, prt, bdrate)"
.br
.ti -1c
.RI "def \fBInterpretResponse\fP (self)"
.br
.ti -1c
.RI "def \fB__str__\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBH\fP"
.br
.ti -1c
.RI "\fBunitH\fP"
.br
.ti -1c
.RI "\fBT\fP"
.br
.ti -1c
.RI "\fBunitT\fP"
.br
.ti -1c
.RI "\fBerr\fP"
.br
.ti -1c
.RI "\fBcmdID\fP"
.br
.ti -1c
.RI "\fBpString\fP"
.br
.ti -1c
.RI "\fBrespMask\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def sensors\&.DHT22\&.__init__ ( self,  prt,  bdrate)"

.SH "Member Function Documentation"
.PP 
.SS "def sensors\&.DHT22\&.__str__ ( self)"

.SS "def sensors\&.DHT22\&.InterpretResponse ( self)"

.PP
.nf
Interpret response list 
.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "sensors\&.DHT22\&.cmdID"

.SS "sensors\&.DHT22\&.err"

.SS "sensors\&.DHT22\&.H"

.SS "sensors\&.DHT22\&.pString"

.SS "sensors\&.DHT22\&.respMask"

.SS "sensors\&.DHT22\&.T"

.SS "sensors\&.DHT22\&.unitH"

.SS "sensors\&.DHT22\&.unitT"


.SH "Author"
.PP 
Generated automatically by Doxygen for SensorNode from the source code\&.
