.TH "Python/SensorNode.py" 3 "Tue Apr 4 2017" "Version 0.2" "SensorNode" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Python/SensorNode.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBSensorNode\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "list \fBSensorNode\&.nodeAddresses\fP = ['A0:A0:A0:A0:A0']"
.br
.ti -1c
.RI "string \fBSensorNode\&.port\fP = '/dev/ttyAMA0'"
.br
.ti -1c
.RI "int \fBSensorNode\&.baudrate\fP = 9600"
.br
.ti -1c
.RI "\fBSensorNode\&.sens\fP = \fBsensors\&.Sensors\fP(port, baudrate)"
.br
.ti -1c
.RI "\fBSensorNode\&.ds\fP = \fBsensors\&.DS18B20\fP(port, baudrate)"
.br
.ti -1c
.RI "\fBSensorNode\&.mv\fP = \fBsensors\&.Movement\fP(port,baudrate)"
.br
.ti -1c
.RI "\fBSensorNode\&.lightA\fP = \fBsensors\&.LightAnalog\fP(port,baudrate)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SensorNode from the source code\&.
