.TH "sensLights" 3 "Mon Apr 3 2017" "Version 0.2" "SensorNode" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sensLights \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBprThresh\fP = 550"
.br
.ti -1c
.RI "string \fBsend_str\fP = '550\\n'"
.br
.ti -1c
.RI "\fBsensorData\fP = ReadSensorData('98:D3:31:FB:31:A6',send_str)"
.br
.ti -1c
.RI "\fBpr\fP = int(re\&.search('<NSL19M51>(\&.*)</NSL19M51>',sensorData)[0])"
.br
.ti -1c
.RI "\fBds18b20\fP = re\&.findall('<DS18B20><ID>(\&.*)</ID><T>(\&.*)\\xc2\\xb0C</T></\fBDS18B20\fP>',sensorData)"
.br
.ti -1c
.RI "\fBdht\fP = re\&.findall('<DHT22><T>(\&.*)\\xc2\\xb0C</T><H>(\&.*)%RH</H></\fBDHT22\fP>',sensorData)"
.br
.ti -1c
.RI "\fBmovement\fP = int(re\&.search('<mv>(\&.*)</mv>',sensorData)\&.group(1))"
.br
.ti -1c
.RI "\fBmoveSenseEnabled\fP = int(re\&.search('<mvSen>(\&.*)</mvSen>',sensorData)\&.group(1))"
.br
.ti -1c
.RI "bool \fBlights\fP = False"
.br
.ti -1c
.RI "bool \fBlightSwitch\fP = True"
.br
.ti -1c
.RI "\fBtime\fP = int(re\&.search('<time>(\&.*)</time>',sensorData)\&.group(1))"
.br
.ti -1c
.RI "\fBshell\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "sensLights\&.dht = re\&.findall('<DHT22><T>(\&.*)\\xc2\\xb0C</T><H>(\&.*)%RH</H></\fBDHT22\fP>',sensorData)"

.SS "sensLights\&.ds18b20 = re\&.findall('<DS18B20><ID>(\&.*)</ID><T>(\&.*)\\xc2\\xb0C</T></\fBDS18B20\fP>',sensorData)"

.SS "bool sensLights\&.lights = False"

.SS "bool sensLights\&.lightSwitch = True"

.SS "sensLights\&.movement = int(re\&.search('<mv>(\&.*)</mv>',sensorData)\&.group(1))"

.SS "sensLights\&.moveSenseEnabled = int(re\&.search('<mvSen>(\&.*)</mvSen>',sensorData)\&.group(1))"

.SS "sensLights\&.pr = int(re\&.search('<NSL19M51>(\&.*)</NSL19M51>',sensorData)[0])"

.SS "int sensLights\&.prThresh = 550"

.SS "string sensLights\&.send_str = '550\\n'"

.SS "sensLights\&.sensorData = ReadSensorData('98:D3:31:FB:31:A6',send_str)"

.SS "sensLights\&.shell"

.SS "sensLights\&.time = int(re\&.search('<time>(\&.*)</time>',sensorData)\&.group(1))"

.SH "Author"
.PP 
Generated automatically by Doxygen for SensorNode from the source code\&.
