.TH "SensorNode" 3 "Thu May 25 2017" "Version 0.2" "SensorNode" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SensorNode \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSensorNode\fP"
.br
.ti -1c
.RI "class \fBThread\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBGetTimeString\fP ()"
.br
.ti -1c
.RI "def \fBUpdateThreads\fP (sensorObj)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBcount\fP = 0"
.br
.ti -1c
.RI "\fBlock\fP = threading\&.Lock()"
.br
.ti -1c
.RI "list \fBthr\fP = []"
.br
.ti -1c
.RI "\fBapp\fP = \fBSensorNode\fP()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def SensorNode\&.GetTimeString ()"

.SS "def SensorNode\&.UpdateThreads ( sensorObj)"

.PP
.nf

.fi
.PP
 
.SH "Variable Documentation"
.PP 
.SS "SensorNode\&.app = \fBSensorNode\fP()"

.SS "int SensorNode\&.count = 0"

.SS "SensorNode\&.lock = threading\&.Lock()"

.SS "list SensorNode\&.thr = []"

.SH "Author"
.PP 
Generated automatically by Doxygen for SensorNode from the source code\&.
