.TH "Python/SensorNode.py" 3 "Thu May 25 2017" "Version 0.2" "SensorNode" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Python/SensorNode.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSensorNode\&.Thread\fP"
.br
.ti -1c
.RI "class \fBSensorNode\&.SensorNode\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBSensorNode\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBSensorNode\&.GetTimeString\fP ()"
.br
.ti -1c
.RI "def \fBSensorNode\&.UpdateThreads\fP (sensorObj)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBSensorNode\&.count\fP = 0"
.br
.ti -1c
.RI "\fBSensorNode\&.lock\fP = threading\&.Lock()"
.br
.ti -1c
.RI "list \fBSensorNode\&.thr\fP = []"
.br
.ti -1c
.RI "\fBSensorNode\&.app\fP = SensorNode()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SensorNode from the source code\&.
