.TH "Sensors" 3 "Thu May 25 2017" "Version 0.2" "SensorNode" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Sensors \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDHT22\fP"
.br
.RI "\fI\fBDHT22\fP class definition\&. \fP"
.ti -1c
.RI "class \fBDS18B20\fP"
.br
.RI "\fI\fBDS18B20\fP class definition\&. \fP"
.ti -1c
.RI "class \fBPhotoresistor\fP"
.br
.RI "\fI\fBPhotoresistor\fP class definition\&. \fP"
.ti -1c
.RI "class \fBSensors\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SensorNode from the source code\&.
