.TH "sensors.LightDigital" 3 "Thu May 25 2017" "Version 0.2" "SensorNode" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sensors.LightDigital \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBreadsensor\&.ReadSensor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, prt, bdrate)"
.br
.ti -1c
.RI "def \fBInterpretResponse\fP (self)"
.br
.ti -1c
.RI "def \fB__str__\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBvalue\fP"
.br
.ti -1c
.RI "\fBnodeMAC\fP"
.br
.ti -1c
.RI "\fBcmdID\fP"
.br
.ti -1c
.RI "\fBpString\fP"
.br
.ti -1c
.RI "\fBrespMask\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def sensors\&.LightDigital\&.__init__ ( self,  prt,  bdrate)"

.SH "Member Function Documentation"
.PP 
.SS "def sensors\&.LightDigital\&.__str__ ( self)"

.SS "def sensors\&.LightDigital\&.InterpretResponse ( self)"

.PP
.nf
Interpret response list 
.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "sensors\&.LightDigital\&.cmdID"

.SS "sensors\&.LightDigital\&.nodeMAC"

.SS "sensors\&.LightDigital\&.pString"

.SS "sensors\&.LightDigital\&.respMask"

.SS "sensors\&.LightDigital\&.value"


.SH "Author"
.PP 
Generated automatically by Doxygen for SensorNode from the source code\&.
