.TH "SerialConn" 3 "Mon Apr 3 2017" "Version 0.2" "SensorNode" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SerialConn \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBser\fP = NewSerialCon('/dev/ttyAMA0', 9600)"
.br
.ti -1c
.RI "\fBresp\fP = ReadSensorDS18B20(\fBser\fP,'A0:A0:A0:A0:A0')"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "SerialConn\&.resp = ReadSensorDS18B20(\fBser\fP,'A0:A0:A0:A0:A0')"

.SS "SerialConn\&.ser = NewSerialCon('/dev/ttyAMA0', 9600)"

.SH "Author"
.PP 
Generated automatically by Doxygen for SensorNode from the source code\&.
