.TH "src/IO/SPI.cpp" 3 "Thu May 25 2017" "Version 0.2" "SensorNode" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/IO/SPI.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'SPI\&.h'\fP
.br
\fC#include <avr/io\&.h>\fP
.br
\fC#include <avr/interrupt\&.h>\fP
.br

.SH "Detailed Description"
.PP 
Project: \fBSensorNode\fP
.PP
\fBSPI\&.cpp\fP
.PP
Created on: Nov 12, 2016
.PP
Author: Matthias Minx
.PP
Revision: 1 
.SH "Author"
.PP 
Generated automatically by Doxygen for SensorNode from the source code\&.
