.TH "src/IO/USART.cpp" 3 "Mon Apr 3 2017" "Version 0.2" "SensorNode" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/IO/USART.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'USART\&.h'\fP
.br
\fC#include <avr/io\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <avr/interrupt\&.h>\fP
.br

.SH "Detailed Description"
.PP 
Project: SensorNode
.PP
\fBUSART\&.cpp\fP
.PP
Created on: Nov 12, 2016
.PP
Author: Matthias Minx
.PP
Revision: 0\&.2 
.SH "Author"
.PP 
Generated automatically by Doxygen for SensorNode from the source code\&.
